name: Build Android
run-name: Build Android
on:
  workflow_dispatch: {}
jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev webkit2gtk-4.1
      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.RELEASE_KEY_PROPERTIES }}
        run: |
          echo $ENCODED_KEYSTORE > keystore_base64.txt
          base64 -d keystore_base64.txt > /home/runner/upload-keystore.jks
          cat << EOF > android/key.properties
          ${{ secrets.RELEASE_KEY_PROPERTIES }}
          EOF
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: app-android
          path: build/app/outputs/apk/release
